


export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';
export const FETCH_USER_LOGOUT = 'FETCH_USER_LOGOUT';
// export const FETCH_USER_SIGNUP = 'FETCH_USER_SIGNUP';

